In [2]:
import pandas as pd
import pygal
from sklearn.cluster import DBSCAN

In [3]:
from IPython.display import display, HTML
base_html = """
<!DOCTYPE html>
<html>
  <head>
  <script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/svg.jquery.js"></script>
  <script type="text/javascript" src="https://kozea.github.io/pygal.js/2.0.x/pygal-tooltips.min.js""></script>
  </head>
  <body>
    <figure>
      {rendered_chart}
    </figure>
  </body>
</html>
"""

In [6]:
dataFrame = pd.read_json(r"C:\Users\GEORGIE\Downloads\MOCK_DATA.json")
dataFrame.head()

,User,TimeStamp,time,hour,minute,second,Longitude,Latitude
0,Joann,2022-07-28,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,-73.960233,10.148976
1,Daphene,2022-07-28,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,103.708957,18.031366
2,Petrina,2022-07-28,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,116.318461,35.063304
3,Vanny,2022-07-28,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,119.526925,35.416734
4,Maurits,2022-07-28,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,error: Please use field('TimeStamp') to access...,54.861927,55.478777